name: workflow.yml

on:
    workflow_dispatch:

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
    - name: Request approval
      uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.PAT }}

  echo:
    needs: approval
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo repository name
      run: |
            echo "Hello, this is the repository: ${{ github.repository }}"